### ISSUE TITLE
Errors on build with OdysseyExt

### ISSUE THREAD

**Issue by CodeRooster001** [exelix11/EditorCore#6]
I keep getting a bunch of errors when I try to build the project with the OdysseyExt folder... I'm probably doing something wrong. The error codes are CS0012s and CS0234s...

**Comment by exelix11** [comment]
try restoring nuget packages

**Comment by CodeRooster001** [comment]
I get this error when I try to run it. It can't seem to find the .bfres file library.
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'BfresLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at OdysseyExt.OdysseyModule.FormLoaded() in C:\Users\(Username)\Desktop\OdysseyEditor-master\GameModule.cs:line 205
   at EditorCore.EditorForm.GamePathAndModelCheck() in C:\Users\(Username)\Desktop\EditorCore-master\EditorCore\EditorForm.cs:line 1080
   at EditorCore.EditorForm.Form1_Load(Object sender, EventArgs e) in C:\Users\Code_Rooster\Desktop\EditorCore-master\EditorCore\EditorForm.cs:line 226
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
